# Change these first
owner: panaris # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: panicc
    url: https://paniccsoftworks.com
  - name: emergency
    url: https://emergencyhelp.eu
  - name: tetteris
    url: https://tetteris.gr
  - name: taptap
    url: https://tap-tap.click

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Check the uptime of my projects."
  navbar:
    - title: Instagram
      href: https://www.instagram.com/panagiotischristoforakis/
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: Email
      href: mailto:panagiotischristoforakis@gmail.com
i18n:
  footer: " "
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
